### ISSUE TITLE
Not able to see the related list

### ISSUE THREAD

**Issue by usirikayalasiva** [CharlesHGong/lightningRelatedListWithFilter#1]
The related list has been loading since I have opened the account and it still showing the loading icon

**Comment by CharlesHGong** [comment]
Hey would you uploads som screen shoots of the problem please.
What's the component's config on the flexi page?

**Comment by Pioneerhardware** [comment]
Hi,

Is there any way of having this appear in the Salesforce App?

**Comment by CharlesHGong** [comment]
> Hi,
> 
> Is there any way of having this appear in the Salesforce App?

Hey @Pioneerhardware , do you mean the SF mobile APP? At this stage salesforce doesn't allow custom lightning component on the SF mobile app. But I can see SF is making that feature in the near future, I'll keep you posted and update this rep once it's out.

**Comment by CharlesHGong** [comment]
> Hi,
> 
> Is there any way of having this appear in the Salesforce App?

Adding a new issue and closing this one.
