### ISSUE TITLE
Component Doesn't load in record page, can't delete

### ISSUE THREAD

**Issue by jameskbw** [CharlesHGong/lightningRelatedListWithFilter#10]
I deployed the components to my dev org today and added to an account lightning record page.  The component shows a continuous loading spinner  and now I can't delete the component.

Any ideas on a step I may have missed?
![2020-09-10 16_23_21-Account Default Record Page - Lightning App Builder](https://user-images.githubusercontent.com/59923636/92799736-0990bd00-f382-11ea-8e2d-9d8fdddbbad2.png)

**Comment by CharlesHGong** [comment]
I think you can fill up the mandatory fields like on the readme page and then you could remove it.

**Comment by jameskbw** [comment]
Thanks, the issue I was running into was the fields attribute.  I was putting a space after the comma and it was showing the spinner non stop.

**Comment by CharlesHGong** [comment]
The issue has been resolved
