### ISSUE TITLE
Attempted Deploy in Prod after testing in Sandbox...no-go

### ISSUE THREAD

**Issue by acxparrish** [CharlesHGong/lightningRelatedListWithFilter#13]
I tried to deploy this in my production environment after testing in sandbox for a while and it gets to **Status: Completed** but then I get **Code coverage issue -- Average test coverage across all Apex Classes and Triggers is 74%, at least 75% test coverage is required**. Not entirely sure if that is on my end or not.

Would love to get this to work in production as it would meet a huge business challenge!

**Comment by CharlesHGong** [comment]
Hey @acxparrish this package has an overall coverage of 90% so I think might be other code in your end.
<img width="757" alt="Screen Shot 2020-12-02 at 7 09 44 am" src="https://user-images.githubusercontent.com/13030456/100791503-72fa0680-346d-11eb-974d-2dfb80bd67cf.png">

**Comment by acxparrish** [comment]
Thanks for the response and sorry to bother. Ran tests in both sandbox and prod and was able to reinstall in sandbox so definitely something up with prod environment.
