### ISSUE TITLE
Test Class issues

### ISSUE THREAD

**Issue by jmmurphey0317** [CharlesHGong/lightningRelatedListWithFilter#5]
The test classes provided in the project wont pass through validation to production

**Comment by CharlesHGong** [comment]
The current test coverage suggest by the CI is at 90%:
![image](https://user-images.githubusercontent.com/13030456/79702777-94e1b700-82ea-11ea-9628-dc0c803f357c.png)

Could you provide a screen shoot of what components did you deploy and the error message please.
