### ISSUE TITLE
Numbers not showing in list 

### ISSUE THREAD

**Issue by qwertyqwq** [CharlesHGong/lightningRelatedListWithFilter#6]
All number fields will not show in the component.

**Comment by fglynn9** [comment]
I have had the same issue.

**Comment by CharlesHGong** [comment]
I think the `lightning:datatable` has changed it's type for number and percent, working on a patch now.

**Comment by CharlesHGong** [comment]
Hey @qwertyqwq  @fglynn9 I've fix the bug in the PR, please let me know whether the issue has been resolved or not.

**Comment by qwertyqwq** [comment]
@CharlesHGong Thank you, it resolved the issue
